# Central configuration for GitHub Actions workflows
# This file contains all version numbers and common configurations used across workflows

versions:
  current: "2025.4.2"
  previous_lta: "9.9.9"
  community_build: "25.9.0.112764"

images:
  staging: "sonarsource/sonarqube"
  public: "sonarqube"

registries:
  gcp_public: "gcr.io/sonarsource-public"
  gcp_staging: "gcr.io/sonarqube-marketplace-provider"

products:
  gcp_public_name: "official-sonarqube-data-center-edition"
  gcp_staging_name: "sonarqube-dce-staging"

