env:
  # see https://github.com/SonarSource/re-terraform-aws-vault/blob/master/orders/bubble-cfamily.yaml
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  DOCKER_USERNAME: VAULT[development/kv/data/docker/sonardockerrw data.username]
  DOCKER_PASSWORD: VAULT[development/kv/data/docker/sonardockerrw data.access_token_rwd]

multi_arch_build_docker_builder: 
  env:
    matrix:
      - version: 9/community
        tag: 9-community
      - version: 9/developer
        tag: 9-developer
      - version: 9/enterprise
        tag: 9-enterprise
      - version: 9/datacenter/app
        tag: 9-datacenter-app
      - version: 9/datacenter/search
        tag: 9-datacenter-search
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  setup_script:
    - docker run -t --rm --privileged tonistiigi/binfmt --install all
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  build_script:
    - echo "Build the ${tag} image supporting two architectures, amd64 and arm64"
    - docker buildx build --platform linux/amd64,linux/arm64 --tag "sonarsource/sonarqube:${tag}" --push ${version}

multi_arch_test_docker_builder:
  matrix:
    - env:
        CIRRUS_ARCH: arm64
    - env:
        CIRRUS_ARCH: amd64
  env:
    matrix:
      - test_name: docker
        tag: 9-community
      - test_name: docker
        tag: 9-developer
      - test_name: docker
        tag: 9-enterprise
      - test_name: docker-compose
        tag: 9-datacenter
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  test_script:
    - sysctl -w vm.max_map_count=524288 # set the recommended memory for ES
    - ./run-tests.sh "sonarsource/sonarqube:${tag}" "${test_name}"
  depends_on: multi_arch_build


