env:
  # see https://github.com/SonarSource/re-terraform-aws-vault/blob/master/orders/bubble-cfamily.yaml
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  DOCKER_USERNAME: VAULT[development/kv/data/docker/sonardockerrw data.username]
  DOCKER_PASSWORD: VAULT[development/kv/data/docker/sonardockerrw data.access_token_rwd]

docker_builder:
  arm_container: # use an arm64 container for running our image
    image: docker
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  build_script: 
    - echo "Build the community image supporting two architectures, amd64 and arm64"
    - docker buildx build --platform linux/amd64,linux/arm64 --tag sonar/sonarqube:9.7.1-community ./9/community # Need to push this image to a private registry: can we use a repo in our artifactory for that? which one? how can we can login our build to it?
  run_script:
    - echo "Test the pull of an arm64-compatible image"
    - docker pull carminevassallo567/sonarqube:9.7.1-community