sonar.projectKey=SonarSource_docker-sonarqube_AYcnOvlJTpBOcQuGEdI5
sonar.sources=commercial-editions/,community-build/,docker-official-images/,agentic-compose-generator/
sonar.organization=sonarsource
sonar.go.coverage.reportPaths=docker-official-images/coverage.out
sonar.test.inclusions=docker-official-images/**/*_test.go,agentic-compose-generator/tests/**
sonar.python.coverage.reportPaths=agentic-compose-generator/coverage.xml
