name: GCP build production

on:
  schedule:
    # Nightly equivalent
    - cron: '0 2 * * *'
  workflow_dispatch:
    inputs:
      trigger_type:
        description: 'Trigger type'
        required: false
        default: 'manual'
        type: choice
        options:
          - manual
          - PUSH_GCP_IMAGES
  release:
    types: [published]
  # TODO: Add support for TRIGGER environment variable equivalent

jobs:
  gcp-build-production:
    permissions:
      id-token: write
      contents: read
    name: GCP build production
    # Only run on nightly, manual trigger with specific type, or releases
    if: |
      github.event_name == 'schedule' || 
      github.event_name == 'release' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.trigger_type == 'PUSH_GCP_IMAGES')
    uses: ./.github/workflows/gcp-build-template.yml
    with:
      gcp_registry: gcr.io/sonarsource-public
      gcp_product_name: official-sonarqube-data-center-edition
      build_type: production
      platforms: linux/amd64
      current_version: 2025.4.1
      public_image_name: sonarqube
