name: Multi-arch build 9.x

on:
  push:
    paths:
      - '9/**/*'
      - '.cirrus/multi-arch-build.sh'
      - '.github/workflows/multi-arch-build-9x.yml'
      - '.github/workflows/multi-arch-build-template.yml'
      - '.github/github_env.yaml'
  pull_request:
    paths:
      - '9/**/*'
      - '.cirrus/multi-arch-build.sh'
      - '.github/workflows/multi-arch-build-9x.yml'
      - '.github/workflows/multi-arch-build-template.yml'
      - '.github/github_env.yaml'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  load-config:
    uses: ./.github/workflows/load-config.yml

  multi-arch-build-9x:
    needs: load-config
    permissions:
      id-token: write
      contents: read
    name: Build 9.x (${{ matrix.version }})
    uses: ./.github/workflows/multi-arch-build-template.yml
    strategy:
      matrix:
        include:
          - version: 9/community
            edition: community
          - version: 9/developer
            edition: developer
          - version: 9/enterprise
            edition: enterprise
          - version: 9/datacenter/app
            edition: datacenter-app
          - version: 9/datacenter/search
            edition: datacenter-search
    with:
      staging_image_name: ${{ needs.load-config.outputs.staging_image }}
      tag: ${{ needs.load-config.outputs.previous_lta_version }}-master-${{ matrix.edition }}
      version: ${{ matrix.version }}
      runs_on: ubuntu-latest-large
