name: Multi-arch build community build

on:
  push:
    paths:
      - 'community-build/*'
      - '.cirrus/multi-arch-build.sh'
      - '.github/workflows/multi-arch-build-community-build.yml'
      - '.github/workflows/multi-arch-build-template.yml'
      - '.github/github_env.yaml'
  pull_request:
    paths:
      - 'community-build/*'
      - '.cirrus/multi-arch-build.sh'
      - '.github/workflows/multi-arch-build-community-build.yml'
      - '.github/workflows/multi-arch-build-template.yml'
      - '.github/github_env.yaml'
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  load-config:
    uses: ./.github/workflows/load-config.yml

  multi-arch-build-community-build:
    needs: load-config
    name: Build community build (${{ matrix.version }})
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/multi-arch-build-template.yml
    strategy:
      matrix:
        include:
          - version: community-build
            edition: community
    with:
      staging_image_name: ${{ needs.load-config.outputs.staging_image }}
      tag: ${{ needs.load-config.outputs.community_build_version }}-master-${{ matrix.edition }}
      version: ${{ matrix.version }}
      runs_on: github-ubuntu-latest-s
