name: Multi-arch test commercial editions

on:
  workflow_run:
    workflows:
      - "Multi-arch build commercial editions"
    types:
      - completed
  workflow_dispatch:

jobs:
  load-config:
    uses: ./.github/workflows/load-config.yml

  multi-arch-test-commercial-editions:
    needs: load-config
    name: Test commercial editions (${{ matrix.test_name }}, ${{ matrix.architecture }})
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    uses: ./.github/workflows/multi-arch-test-template.yml
    strategy:
      matrix:
        include:
          - test_name: docker
            edition: developer
            architecture: amd64
          - test_name: docker
            edition: developer
            architecture: arm64
          - test_name: docker
            edition: enterprise
            architecture: amd64
          - test_name: docker
            edition: enterprise
            architecture: arm64
          - test_name: docker-compose
            edition: datacenter
            architecture: amd64
          - test_name: docker-compose
            edition: datacenter
            architecture: arm64
    with:
      staging_image_name: ${{ needs.load-config.outputs.staging_image }}
      tag: ${{ needs.load-config.outputs.current_version }}-master-${{ matrix.edition }}
      test_name: ${{ matrix.test_name }}
      architecture: ${{ matrix.architecture }}
      runs_on: ${{ matrix.architecture == 'arm64' && 'ubuntu-24.04-arm-large' || 'ubuntu-24.04-large' }}
