name: Multi-arch test commercial editions

on:
  workflow_run:
    workflows:
      - "Multi-arch build commercial editions"
    types:
      - completed
  push:
  schedule:
    # Nightly test equivalent (adjust time as needed)
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  multi-arch-test-commercial-editions:
    name: Test commercial editions (${{ matrix.test_name }}, ${{ matrix.architecture }})
    permissions:
      id-token: write
      contents: read
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' || github.event_name == 'push' }}
    uses: ./.github/workflows/multi-arch-test-template.yml
    strategy:
      matrix:
        architecture: [amd64, arm64]
        include:
          - test_name: docker
            tag: 2025.4.1-master-developer
          - test_name: docker
            tag: 2025.4.1-master-enterprise
          - test_name: docker-compose
            tag: 2025.4.1-master-datacenter
    with:
      staging_image_name: sonarsource/sonarqube
      tag: ${{ matrix.tag }}
      test_name: ${{ matrix.test_name }}
      architecture: ${{ matrix.architecture }}
      runs_on: ${{ matrix.architecture == 'arm64' && 'ubuntu-24.04-arm-large' || 'ubuntu-24.04-large' }}
