name: Private scan

on:
  workflow_run:
    workflows:
      - "Multi-arch build 9.x"
      - "Multi-arch build commercial editions"
    types:
      - completed
  workflow_dispatch:

jobs:
  private-scan:
    name: Private scan
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/mend-scan-template.yml
    with:
      image_name: sonarsource/sonarqube
      tags: '["9.9.9-master-datacenter-app", "2025.4.1-master-datacenter-app"]'
      scan_type: private
      platform: amd64
      ws_product_name: SonarSource/docker-sonarqube
      needs_docker_login: true
