name: Private scan

on:
  workflow_run:
    workflows:
      - "Multi-arch build 9.x"
      - "Multi-arch build commercial editions"
    types:
      - completed
  workflow_dispatch:

jobs:
  load-config:
    uses: ./.github/workflows/load-config.yml

  private-scan:
    needs: load-config
    name: Private scan
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/mend-scan-template.yml
    with:
      image_name: ${{ needs.load-config.outputs.staging_image }}
      tags: '["${{ needs.load-config.outputs.previous_lta_version }}-master-datacenter-app", "${{ needs.load-config.outputs.current_version }}-master-datacenter-app"]'
      scan_type: private
      platform: amd64
      ws_product_name: SonarSource/docker-sonarqube
      needs_docker_login: true
