name: Public scan

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  load-config:
    uses: ./.github/workflows/load-config.yml

  public-scan:
    needs: load-config
    name: Public scan
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/mend-scan-template.yml
    with:
      image_name: ${{ needs.load-config.outputs.public_image }}
      tags: '["${{ needs.load-config.outputs.previous_lta_version }}-datacenter-app", "${{ needs.load-config.outputs.current_version }}-datacenter-app"]'
      scan_type: public
      platform: amd64
      ws_product_name: SonarSource/docker-sonarqube
      needs_docker_login: false
