on:
  workflow_call:
    
name: go test the official images generator
jobs:
  go-test:
    runs-on: ubuntu-latest-large
    permissions:
      id-token: write
      pull-requests: read
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Go based on go.mod
      uses: actions/setup-go@v4
      with:
        go-version-file: docker-official-images/go.mod
    - name: Run tests
      run: go test ./... -coverprofile=coverage.out
      working-directory: docker-official-images/
    - name: Upload coverage file
      uses: actions/upload-artifact@v4
      with:
        name: docker-official-images-coverage-${{ github.sha }}
        path: docker-official-images/coverage.out
        retention-days: 1